/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AITagSuggestion: typeof import('./src/components/article/AITagSuggestion.vue')['default']
    ArticleImportDialog: typeof import('./src/components/article/ArticleImportDialog.vue')['default']
    ArticleRecommendations: typeof import('./src/components/article/ArticleRecommendations.vue')['default']
    BacklinksPanel: typeof import('./src/components/article/BacklinksPanel.vue')['default']
    BottomTabBar: typeof import('./src/components/mobile/BottomTabBar.vue')['default']
    BreadcrumbNav: typeof import('./src/components/misc/BreadcrumbNav.vue')['default']
    CommentSection: typeof import('./src/components/article/CommentSection.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FlashcardFlip: typeof import('./src/components/flashcard/FlashcardFlip.vue')['default']
    HotArticleCard: typeof import('./src/components/article/HotArticleCard.vue')['default']
    KnowledgeGraphPanel: typeof import('./src/components/knowledge/KnowledgeGraphPanel.vue')['default']
    LocalGraphPanel: typeof import('./src/components/article/LocalGraphPanel.vue')['default']
    MobileContextMenu: typeof import('./src/components/mobile/MobileContextMenu.vue')['default']
    NotificationBell: typeof import('./src/components/article/NotificationBell.vue')['default']
    QueryBlockRenderer: typeof import('./src/components/article/QueryBlockRenderer.vue')['default']
    RAGAnalysisPanel: typeof import('./src/components/rag/RAGAnalysisPanel.vue')['default']
    RAGChatPanel: typeof import('./src/components/rag/RAGChatPanel.vue')['default']
    RAGInput: typeof import('./src/components/rag/RAGInput.vue')['default']
    RAGMessage: typeof import('./src/components/rag/RAGMessage.vue')['default']
    RAGSourceCard: typeof import('./src/components/rag/RAGSourceCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutHelpDialog: typeof import('./src/components/misc/ShortcutHelpDialog.vue')['default']
    SwipeDeleteItem: typeof import('./src/components/mobile/SwipeDeleteItem.vue')['default']
    TagTreePanel: typeof import('./src/components/article/TagTreePanel.vue')['default']
    TemplateSelector: typeof import('./src/components/article/TemplateSelector.vue')['default']
    TimestampNav: typeof import('./src/components/video/TimestampNav.vue')['default']
    TocSidebar: typeof import('./src/components/article/TocSidebar.vue')['default']
    VersionHistory: typeof import('./src/components/article/VersionHistory.vue')['default']
    VideoBindPanel: typeof import('./src/components/editor/VideoBindPanel.vue')['default']
    VideoPlayer: typeof import('./src/components/video/VideoPlayer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
